### ISSUE TITLE
Reorganization of client-side repositories

### ISSUE THREAD

**Issue by elfey** [feathersjs/client#137]
Right now there's a bit of confusion for newcomers - most of us learn the server bit of feathers first, and then jump over to implementing it on the client.

However, the client has a completely different structure than the server and (in my opinion) is a little less organized than its relative (the server).

What if both the client and server had a similar structure across the board?

For example:
- **Client**
  - `feathers-client` _(core)_
  - `feathers-hooks-client`
  - `feathers-rest-client`
  - `feathers-socketio-client`
  - `feathers-authentication-client`
- **Server**
  - `feathers` _(core)_
  - `feathers-hooks`
  - `feathers-rest`
  - `feathers-socketio`
  - `feathers-authentication`

I hope you can see the pattern; for every server package, there's a client counterpart.

As for setting these up, it would work the same way on the client as it does on the server; you have your core `feathers` or `feathers-client` and you plug your `feathers-*` or `feathers-*-client` into each one, respectively.

Yes, this means more dependencies and repositories. I think though, that it will create a system that is more unified and easy to understand across the board because setup will be relatively similar on both frontend and backend.

That's good for individual developers and teams in general.

It means less confusion, more building.

**Comment by marshallswain** [comment]
Familiarity is definitely something worth striving for.  We originally had everything at `feathers-module/client`, but decided to split out the client for `feathers-authentication` and create `feathers-authentication-client`, which has introduced the discrepancy.

`feathers-hooks` doesn't have its own client version, and it will be integrated into Feathers core sometime in the Buzzard release.

That will leave us in a state like this:

*Client*
```js
import feathers from 'feathers/client';
import hooks from 'feathers/hooks';
import rest from 'feathers-rest/client';
import socketio from 'feathers-socketio/client';
import auth from 'feathers-authentication-client';
```

*Server*
```js
const feathers = require('feathers');
const hooks = require('feathers/hooks');
const rest = require('feathers-rest');
const socketio = require('feathers-socketio');
const auth = require('feathers-authentication');
```

**Comment by daffl** [comment]
This is a good suggestion. I wanted to create `feathers-rest-client`, `feathers-socketio-client` and `feathers-primus-client` for a while now (and probably should've created an issue for it so thank you for that 😄).

I am however suggesting to defer this to the next release (after Auk) however for the following reasons:

- There will be no more `feathers/client` since Feathers will be framework independent. This means that core Feathers will work the exact same on both sides and you will just configure either the framework you want (probably Express or Koa for now) on the server and the connection you want to use on the client like it is already done. See https://github.com/feathersjs/feathers/issues/258
- as @marshallswain pointed out, `feathers-hooks` works the same on both sides. In the next version it will also become part of core so it does not need to be required or configured separately anymore. See https://github.com/feathersjs/feathers/issues/408

**Comment by mz103** [comment]
@marshallswain valid points, and thanks for reminding me about `feathers-hooks` being a part of core.

@daffl those are great ideas! Everything fits together nicely with that model of thinking.
